# Generated by Django 3.2.4 on 2021-07-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('title2', models.CharField(max_length=1255)),
                ('image', models.ImageField(upload_to='background')),
            ],
            options={
                'verbose_name': 'home page',
                'verbose_name_plural': 'home pages',
            },
        ),
    ]
