# Generated by Django 3.2.4 on 2021-07-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contactmodel_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='message',
            new_name='text',
        ),
    ]
