# Generated by Django 3.2.4 on 2021-07-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_message_contactmodel_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homemodel',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='title2',
        ),
        migrations.AddField(
            model_name='homemodel',
            name='title_1',
            field=models.CharField(default=1, max_length=255, verbose_name='title_1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homemodel',
            name='title_2',
            field=models.CharField(default=1, max_length=1255, verbose_name='title_2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='image',
            field=models.ImageField(upload_to='background', verbose_name='image'),
        ),
    ]
