# Generated by Django 3.2.4 on 2021-07-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210717_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodel',
            name='title_1_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title_1'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='title_1_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title_1'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='title_2_en',
            field=models.CharField(max_length=1255, null=True, verbose_name='title_2'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='title_2_ru',
            field=models.CharField(max_length=1255, null=True, verbose_name='title_2'),
        ),
    ]
