# Generated by Django 3.2.4 on 2021-07-22 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_alter_ordermodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='user',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='user',
            field=models.ManyToManyField(related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
