# Generated by Django 3.2.4 on 2021-06-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brandmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='model',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
