# Generated by Django 3.2.4 on 2021-07-13 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_gendermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='gender', to='products.gendermodel'),
            preserve_default=False,
        ),
    ]
