# Generated by Django 3.2.4 on 2021-07-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_productsmodel_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenderModel',
        ),
    ]
