# Generated by Django 3.2.4 on 2021-07-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210715_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeModel',
        ),
    ]
