# Generated by Django 3.2.4 on 2021-07-16 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_colorsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='products.gendermodel'),
        ),
    ]
