# Generated by Django 3.2.4 on 2021-07-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productsmodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='colors',
            field=models.ManyToManyField(related_name='products', to='products.ColorsModel'),
        ),
    ]
