# Generated by Django 3.2.4 on 2021-07-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productsmodel_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='colors',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='products.ColorsModel'),
        ),
    ]
