# Generated by Django 3.2.4 on 2021-07-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_productsmodel_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='colors',
            field=models.ManyToManyField(related_name='products', to='products.ColorsModel'),
        ),
    ]
