# Generated by Django 3.2.4 on 2021-07-17 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0019_alter_productsmodel_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='image',
            field=models.ImageField(upload_to='brands', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='title',
            field=models.CharField(max_length=550, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='title',
            field=models.CharField(max_length=550, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='colorsmodel',
            name='code',
            field=models.CharField(max_length=12, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='colorsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='colorsmodel',
            name='title',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='comment',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='name',
            field=models.CharField(max_length=30, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.productsmodel', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='gendermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='gendermodel',
            name='title',
            field=models.CharField(max_length=550, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productsmodel', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(max_length=550, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand', to='products.brandmodel', verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.categorymodel', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='colors',
            field=models.ManyToManyField(related_name='products', to='products.ColorsModel', verbose_name='colors'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='products.gendermodel', verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='model',
            field=models.CharField(max_length=30, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='price',
            field=models.FloatField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='real_price',
            field=models.FloatField(default=0, verbose_name='real_price'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='sizes',
            field=models.ManyToManyField(related_name='products', to='products.SizeModel', verbose_name='sizes'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='products.ProductTagModel', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='title',
            field=models.CharField(max_length=550, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='wishlist'),
        ),
        migrations.AlterField(
            model_name='producttagmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='producttagmodel',
            name='title',
            field=models.CharField(max_length=550, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='sizemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='sizemodel',
            name='title',
            field=models.CharField(max_length=3, verbose_name='title'),
        ),
    ]
