# Generated by Django 3.2.4 on 2021-07-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20210717_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsmodel',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
