# Generated by Django 3.2.4 on 2021-07-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_productsmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendermodel',
            name='title_en',
            field=models.CharField(max_length=550, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='gendermodel',
            name='title_ru',
            field=models.CharField(max_length=550, null=True, verbose_name='title'),
        ),
    ]
