# Generated by Django 3.2.4 on 2021-07-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20210719_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductModel',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='title_en',
            field=models.CharField(max_length=550, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='title_ru',
            field=models.CharField(max_length=550, null=True, verbose_name='title'),
        ),
    ]
