# Generated by Django 3.2.4 on 2021-07-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20210719_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
