# Generated by Django 3.2.4 on 2021-08-06 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20210719_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='products.brandmodel', verbose_name='brand'),
        ),
    ]
