# Generated by Django 3.2.4 on 2021-08-06 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_productsmodel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.brandmodel', verbose_name='brand'),
        ),
    ]
